apiVersion: csdp.codefresh.io/v1
kind: PromotionFlow
metadata:
  name: hotfix
  annotations:
    version: 0.0.3
    description: 'hotfix'
spec:
  triggerEnvironment: dev
  postTrigger: 'post-action'
  steps:
  - environment: production
    dependsOn:
    - dev
    policy:
      preAction: 'pre-action'
      postAction: 'smoketests'
      action: commit
  
